### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by zqf03118** [heng1025/chatGPT-wechat-official#1]
请问ConversationId和Engine填写什么？
Engine是text-davinci-003模型吗

**Comment by heng1025** [comment]
> 请问ConversationId和Engine填写什么？ Engine是text-davinci-003模型吗

目前没作用，另外 默认模型 已被官方禁用，具体的请参考[chatgpt api](https://github.com/acheong08/ChatGPT)

**Comment by zqf03118** [comment]
问一个其他问题啊，微信公众号有5秒超时就报错的问题，我看你解决方案是主动给用户发消息，你是公众号已经认证过了吗，我看我的没认证，运行你的chat代码就会报48001错误，好像是没有主动给用户发消息的权限

**Comment by heng1025** [comment]
> 问一个其他问题啊，微信公众号有5秒超时就报错的问题，我看你解决方案是主动给用户发消息，你是公众号已经认证过了吗，我看我的没认证，运行你的chat代码就会报48001错误，好像是没有主动给用户发消息的权限

我使用的是测试号😓
