### ISSUE TITLE
wxrequest没有appid属性

### ISSUE THREAD

**Issue by tutan123** [heng1025/chatGPT-wechat-official#5]
你好，我下载了最新的代码在跑，这个报这个错。 之前gpt3.5版本没有这个错误，请问要怎么解决呀
![image](https://user-images.githubusercontent.com/9970427/228220650-62f13a52-7b6c-4480-b014-cd82b504604d.png)

**Comment by heng1025** [comment]
之前用的是config.ini配置文件，现在改为使用环境变量了

**Comment by tutan123** [comment]
我现在用的就是.env，但是不知道为什么运行的时候识别不出来

**Comment by heng1025** [comment]
环境变量加载问题，已处理
